---
title: "Atlantis Subsidence (Atlans)"
---

Atlantis is a modelling environment which is implemented in the [Julia programming language](https://julialang.org/). The source code can found in the [Atlans repository](https://gitlab.com/deltares/subsidence/atlans.jl.git).

Atlantis can be used to create soil subsidence projections based on 3D voxelmodels of the subsurface buildup. Subsidence is calculated per 1D subsurface column as the sum of a combination of three processes: [compaction](core/compaction.qmd), [oxidation](core/oxidation.qmd) and [shrinkage](core/shrinkage.qmd). In general, Atlantis does not consider horizontal interaction between individual columns. Currently, the only horizontal interaction is the possibility to apply a periodic groundwater table lowering based on the median subsidence within a regional area (for example within weir areas).

Besides the 3D subsurface model, the most important input is a groundwater table, typically a mean lowest groundwater table (i.e. GLG). This groundwater table is used to determine the part of the subsurface column where the oxidation and shrinkage processes contribute to the subsidence. Furthermore, calculations of compaction use the groundwater table to determine water- and exchange pore-pressures. The modelling concepts and equations are explained further on the [Atlantis](core/index.qmd) page and an explanation of the installation, along with examples of the usage can be found on the [Usage](usage/index.qmd) page.
